//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RobiPosMapper.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class Area
    {
        public Area()
        {
            this.Districts = new HashSet<District>();
            this.Retailers = new HashSet<Retailer>();
        }
    
        public int AreaId { get; set; }
        public string AreaName { get; set; }
        public int RegionId { get; set; }
    
        public virtual Region Region { get; set; }
        public virtual ICollection<District> Districts { get; set; }
        public virtual ICollection<Retailer> Retailers { get; set; }
    }
}
