//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RobiPosMapper.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class Region
    {
        public Region()
        {
            this.Areas = new HashSet<Area>();
            this.Retailers = new HashSet<Retailer>();
        }
    
        public int RegionId { get; set; }
        public string RegionName { get; set; }
    
        public virtual ICollection<Area> Areas { get; set; }
        public virtual ICollection<Retailer> Retailers { get; set; }
    }
}
