//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RobiPosMapper.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class Retailer
    {
        public Retailer()
        {
            this.ElMsisdns = new HashSet<ElMsisdn>();
            this.SimPosCodes = new HashSet<SimPosCode>();
        }
    
        public int RetailerId { get; set; }
        public string RetailerName { get; set; }
        public string Address { get; set; }
        public Nullable<int> RegionId { get; set; }
        public Nullable<int> AreaId { get; set; }
        public Nullable<int> ThanaId { get; set; }
        public Nullable<int> WardId { get; set; }
        public Nullable<int> MauzaId { get; set; }
        public Nullable<int> VillageId { get; set; }
        public Nullable<bool> IsElPos { get; set; }
        public Nullable<bool> IsSimPos { get; set; }
        public Nullable<bool> IsScPos { get; set; }
        public Nullable<decimal> Latitude { get; set; }
        public Nullable<decimal> Longitude { get; set; }
        public Nullable<decimal> AccuracyLevel { get; set; }
        public Nullable<int> VisitDayId { get; set; }
        public string DefaultPhotoName { get; set; }
        public Nullable<int> PosStructureId { get; set; }
        public Nullable<int> ShopSignageId { get; set; }
        public Nullable<int> ShopTypeId { get; set; }
        public Nullable<int> RspId { get; set; }
        public Nullable<System.DateTime> DsrActivityDateTime { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<System.DateTime> CreateDateTime { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public Nullable<int> ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDateTime { get; set; }
        public string Remarks { get; set; }
        public Nullable<int> RetailerStatusId { get; set; }
        public Nullable<bool> IsVerifiedByDsrs { get; set; }
        public Nullable<System.DateTime> DsrsVerificationDateTime { get; set; }
        public Nullable<int> DsrId { get; set; }
        public Nullable<bool> IsApartments { get; set; }
        public Nullable<bool> IsSlums { get; set; }
        public Nullable<bool> IsSemiUrbunHousing { get; set; }
        public Nullable<bool> IsRuralHousing { get; set; }
        public Nullable<bool> IsShoppingMall { get; set; }
        public Nullable<bool> IsRetailHub { get; set; }
        public Nullable<bool> IsMobileDeviceMarket { get; set; }
        public Nullable<bool> IsBazaar { get; set; }
        public Nullable<bool> IsOfficeArea { get; set; }
        public Nullable<bool> IsGarmentsMajorityArea { get; set; }
        public Nullable<bool> IsGeneralIndustrialArea { get; set; }
        public Nullable<bool> IsUrbanTransitPoints { get; set; }
        public Nullable<bool> IsRuralTransitPoints { get; set; }
        public Nullable<bool> IsUrbanYouthHangouts { get; set; }
        public Nullable<bool> IsSemiUrbanYouthHangouts { get; set; }
        public Nullable<bool> IsRuralYouthHangouts { get; set; }
        public Nullable<int> WorkingId { get; set; }
        public string WorkingFileName { get; set; }
        public Nullable<int> QrCodeId { get; set; }
        public Nullable<int> PosCategoryId { get; set; }
        public Nullable<bool> IsTouristDestinations { get; set; }
        public Nullable<int> IsPrinted { get; set; }
        public Nullable<int> IsDistributed { get; set; }
        public Nullable<System.DateTime> PrintDate { get; set; }
        public Nullable<System.DateTime> DistributionDate { get; set; }
    
        public virtual ICollection<ElMsisdn> ElMsisdns { get; set; }
        public virtual Mauza Mauza { get; set; }
        public virtual Person Person { get; set; }
        public virtual PosStructure PosStructure { get; set; }
        public virtual RSP RSP { get; set; }
        public virtual ShopSignage ShopSignage { get; set; }
        public virtual ShopType ShopType { get; set; }
        public virtual Thana Thana { get; set; }
        public virtual Village Village { get; set; }
        public virtual VisitDay VisitDay { get; set; }
        public virtual Ward Ward { get; set; }
        public virtual ICollection<SimPosCode> SimPosCodes { get; set; }
        public virtual Area Area { get; set; }
        public virtual Region Region { get; set; }
    }
}
