//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RobiPosMapper.DataAccess
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class RobiPosMappingEntities : DbContext
    {
        public RobiPosMappingEntities()
            : base("name=RobiPosMappingEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<Area> Areas { get; set; }
        public DbSet<District> Districts { get; set; }
        public DbSet<Division> Divisions { get; set; }
        public DbSet<ElMsisdn> ElMsisdns { get; set; }
        public DbSet<Language> Languages { get; set; }
        public DbSet<Locality> Localities { get; set; }
        public DbSet<Mauza> Mauzas { get; set; }
        public DbSet<Person> People { get; set; }
        public DbSet<PersonType> PersonTypes { get; set; }
        public DbSet<PosStructure> PosStructures { get; set; }
        public DbSet<PosType> PosTypes { get; set; }
        public DbSet<QrCode> QrCodes { get; set; }
        public DbSet<Region> Regions { get; set; }
        public DbSet<Retailer> Retailers { get; set; }
        public DbSet<RetailerPhoto> RetailerPhotoes { get; set; }
        public DbSet<RSP> RSPs { get; set; }
        public DbSet<ShopSignage> ShopSignages { get; set; }
        public DbSet<ShopType> ShopTypes { get; set; }
        public DbSet<SimPosCode> SimPosCodes { get; set; }
        public DbSet<sysdiagram> sysdiagrams { get; set; }
        public DbSet<Thana> Thanas { get; set; }
        public DbSet<User> Users { get; set; }
        public DbSet<UserType> UserTypes { get; set; }
        public DbSet<Village> Villages { get; set; }
        public DbSet<VisitDay> VisitDays { get; set; }
        public DbSet<Ward> Wards { get; set; }
        public DbSet<WeekDay> WeekDays { get; set; }
        public DbSet<View_1> View_1 { get; set; }
    }
}
