//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RobiPosMapper.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class ShopType
    {
        public ShopType()
        {
            this.Retailers = new HashSet<Retailer>();
        }
    
        public int ShopTypeId { get; set; }
        public string ShopTypeName { get; set; }
    
        public virtual ICollection<Retailer> Retailers { get; set; }
    }
}
