//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RobiPosMapper.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class Thana
    {
        public Thana()
        {
            this.Retailers = new HashSet<Retailer>();
            this.Wards = new HashSet<Ward>();
        }
    
        public int ThanaId { get; set; }
        public string ThanaName { get; set; }
        public Nullable<int> DistrictId { get; set; }
        public Nullable<int> AreaId { get; set; }
    
        public virtual District District { get; set; }
        public virtual ICollection<Retailer> Retailers { get; set; }
        public virtual ICollection<Ward> Wards { get; set; }
    }
}
