//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RobiPosMapper.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class User
    {
        public int UserId { get; set; }
        public string FullName { get; set; }
        public string LoginName { get; set; }
        public string LoginPassword { get; set; }
        public Nullable<int> LanguageId { get; set; }
        public Nullable<int> UserTypeId { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public Nullable<System.DateTime> ModifyDate { get; set; }
        public Nullable<int> Msisdn { get; set; }
        public Nullable<int> ParentId { get; set; }
    
        public virtual Language Language { get; set; }
        public virtual UserType UserType { get; set; }
    }
}
