//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RobiPosMapper.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ward
    {
        public Ward()
        {
            this.Mauzas = new HashSet<Mauza>();
            this.Retailers = new HashSet<Retailer>();
        }
    
        public int WardId { get; set; }
        public string WardName { get; set; }
        public Nullable<int> ThanaId { get; set; }
    
        public virtual ICollection<Mauza> Mauzas { get; set; }
        public virtual ICollection<Retailer> Retailers { get; set; }
        public virtual Thana Thana { get; set; }
    }
}
